# Generated by Django 4.0.6 on 2022-07-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('imdb', models.FloatField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('publishdate', models.DateField()),
                ('country', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('genre', models.ManyToManyField(to='firstapp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('serialid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='firstapp.serial')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=1000, null=True)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='firstapp.serial')),
            ],
        ),
    ]
