# Generated by Django 4.0.6 on 2022-07-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='serialid',
            new_name='serial',
        ),
    ]
