# Generated by Django 4.0.6 on 2022-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_serialid_image_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.TextField(),
        ),
    ]
